// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package main

import (
	"database/sql"
)

type Blog struct {
	Idblogs                  int32
	ForumthreadIdforumthread int32
	UsersIdusers             int32
	LanguageIdlanguage       int32
	Blog                     sql.NullString
	Written                  sql.NullTime
}

type Blogssearch struct {
	BlogsIdblogs                   int32
	SearchwordlistIdsearchwordlist int32
}

type Bookmark struct {
	Idbookmarks  int32
	UsersIdusers int32
	List         sql.NullString
}

type Comment struct {
	Idcomments               int32
	ForumthreadIdforumthread int32
	UsersIdusers             int32
	LanguageIdlanguage       int32
	Written                  sql.NullTime
	Text                     sql.NullString
}

type Commentssearch struct {
	SearchwordlistIdsearchwordlist int32
	CommentsIdcomments             int32
}

type Faq struct {
	Idfaq                        int32
	FaqcategoriesIdfaqcategories int32
	LanguageIdlanguage           int32
	UsersIdusers                 int32
	Answer                       sql.NullString
	Question                     sql.NullString
}

type Faqcategory struct {
	Idfaqcategories int32
	Name            sql.NullString
}

type Forumcategory struct {
	Idforumcategory              int32
	ForumcategoryIdforumcategory int32
	Title                        sql.NullString
	Description                  sql.NullString
}

type Forumthread struct {
	Idforumthread          int32
	Firstpost              int32
	Lastposter             int32
	ForumtopicIdforumtopic int32
	Comments               sql.NullInt32
	Lastaddition           sql.NullTime
	Locked                 sql.NullBool
}

type Forumtopic struct {
	Idforumtopic                 int32
	Lastposter                   int32
	ForumcategoryIdforumcategory int32
	Title                        sql.NullString
	Description                  sql.NullString
	Threads                      sql.NullInt32
	Comments                     sql.NullInt32
	Lastaddition                 sql.NullTime
}

type Imageboard struct {
	Idimageboard           int32
	ImageboardIdimageboard int32
	Title                  sql.NullString
	Description            sql.NullString
}

type Imagepost struct {
	Idimagepost              int32
	ForumthreadIdforumthread int32
	UsersIdusers             int32
	ImageboardIdimageboard   int32
	Posted                   sql.NullTime
	Description              sql.NullString
	Thumbnail                sql.NullString
	Fullimage                sql.NullString
}

type Language struct {
	Idlanguage int32
	Nameof     sql.NullString
}

type Linker struct {
	Idlinker                       int32
	LanguageIdlanguage             int32
	UsersIdusers                   int32
	LinkercategoryIdlinkercategory int32
	ForumthreadIdforumthread       int32
	Title                          sql.NullString
	Url                            sql.NullString
	Description                    sql.NullString
	Listed                         sql.NullTime
}

type Linkercategory struct {
	Idlinkercategory int32
	Title            sql.NullString
}

type Linkerqueue struct {
	Idlinkerqueue                  int32
	LanguageIdlanguage             int32
	UsersIdusers                   int32
	LinkercategoryIdlinkercategory int32
	Title                          sql.NullString
	Url                            sql.NullString
	Description                    sql.NullString
}

type Linkersearch struct {
	SearchwordlistIdsearchwordlist int32
	LinkerIdlinker                 int32
}

type Permission struct {
	Idpermissions int32
	UsersIdusers  int32
	Section       sql.NullString
	Level         sql.NullString
}

type Preference struct {
	Idpreferences      int32
	LanguageIdlanguage int32
	UsersIdusers       int32
	Emailforumupdates  sql.NullBool
}

type Searchwordlist struct {
	Idsearchwordlist int32
	Word             sql.NullString
}

type SearchwordlistHasLinker struct {
	SearchwordlistIdsearchwordlist int32
	LinkerIdlinker                 int32
}

type Sidtable struct {
	Idsidtable   int32
	UsersIdusers int32
	Logintime    sql.NullTime
	Sid          sql.NullString
}

type Sitenews struct {
	Idsitenews               int32
	ForumthreadIdforumthread int32
	LanguageIdlanguage       int32
	UsersIdusers             int32
	News                     sql.NullString
	Occured                  sql.NullTime
}

type Sitenewssearch struct {
	SitenewsIdsitenews             int32
	SearchwordlistIdsearchwordlist int32
}

type Topicrestriction struct {
	ForumtopicIdforumtopic int32
	Viewlevel              sql.NullInt32
	Replylevel             sql.NullInt32
	Newthreadlevel         sql.NullInt32
	Seelevel               sql.NullInt32
	Invitelevel            sql.NullInt32
	Readlevel              sql.NullInt32
	Modlevel               sql.NullInt32
	Adminlevel             sql.NullInt32
}

type User struct {
	Idusers  int32
	Email    sql.NullString
	Passwd   sql.NullString
	Username sql.NullString
}

type Userlang struct {
	Iduserlang         int32
	UsersIdusers       int32
	LanguageIdlanguage int32
}

type Userstopiclevel struct {
	UsersIdusers           int32
	ForumtopicIdforumtopic int32
	Level                  sql.NullInt32
	Invitemax              sql.NullInt32
}

type Writing struct {
	Idwriting                        int32
	UsersIdusers                     int32
	ForumthreadIdforumthread         int32
	LanguageIdlanguage               int32
	WritingcategoryIdwritingcategory int32
	Title                            sql.NullString
	Published                        sql.NullTime
	Writting                         sql.NullString
	Abstract                         sql.NullString
	Private                          sql.NullBool
}

type Writingcategory struct {
	Idwritingcategory                int32
	WritingcategoryIdwritingcategory int32
	Title                            sql.NullString
	Description                      sql.NullString
}

type Writingsearch struct {
	SearchwordlistIdsearchwordlist int32
	WritingIdwriting               int32
}

type Writtingapproveduser struct {
	WritingIdwriting int32
	UsersIdusers     int32
	Readdoc          sql.NullBool
	Editdoc          sql.NullBool
}

type _1OldForumthread struct {
	Idforumthread          int32
	ForumtopicIdforumtopic int32
}

type _1OldForumtopic struct {
	Idforumtopic                 int32
	ForumcategoryIdforumcategory int32
	Title                        sql.NullString
	Description                  sql.NullString
}
