// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries-imagebbs.sql

package main

import (
	"context"
	"database/sql"
)

const createImageBoard = `-- name: CreateImageBoard :exec
INSERT INTO imageboard (imageboard_idimageboard, title, description) VALUES (?, ?, ?)
`

type CreateImageBoardParams struct {
	ImageboardIdimageboard int32
	Title                  sql.NullString
	Description            sql.NullString
}

func (q *Queries) CreateImageBoard(ctx context.Context, arg CreateImageBoardParams) error {
	_, err := q.db.ExecContext(ctx, createImageBoard, arg.ImageboardIdimageboard, arg.Title, arg.Description)
	return err
}

const createImagePost = `-- name: CreateImagePost :execlastid
INSERT INTO imagepost (imageboard_idimageboard, thumbnail, fullimage, users_idusers, description, posted)
VALUES (?, ?, ?, ?, ?, NOW())
`

type CreateImagePostParams struct {
	ImageboardIdimageboard int32
	Thumbnail              sql.NullString
	Fullimage              sql.NullString
	UsersIdusers           int32
	Description            sql.NullString
}

func (q *Queries) CreateImagePost(ctx context.Context, arg CreateImagePostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createImagePost,
		arg.ImageboardIdimageboard,
		arg.Thumbnail,
		arg.Fullimage,
		arg.UsersIdusers,
		arg.Description,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getAllBoardsByParentBoardId = `-- name: GetAllBoardsByParentBoardId :many
SELECT idimageboard, imageboard_idimageboard, title, description
FROM imageboard
WHERE imageboard_idimageboard = ?
`

func (q *Queries) GetAllBoardsByParentBoardId(ctx context.Context, imageboardIdimageboard int32) ([]*Imageboard, error) {
	rows, err := q.db.QueryContext(ctx, getAllBoardsByParentBoardId, imageboardIdimageboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Imageboard
	for rows.Next() {
		var i Imageboard
		if err := rows.Scan(
			&i.Idimageboard,
			&i.ImageboardIdimageboard,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllImageBoards = `-- name: GetAllImageBoards :many
SELECT b.idimageboard, b.imageboard_idimageboard, b.title, b.description
FROM imageboard b
`

func (q *Queries) GetAllImageBoards(ctx context.Context) ([]*Imageboard, error) {
	rows, err := q.db.QueryContext(ctx, getAllImageBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Imageboard
	for rows.Next() {
		var i Imageboard
		if err := rows.Scan(
			&i.Idimageboard,
			&i.ImageboardIdimageboard,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllImagePostsByBoardIdWithAuthorUsernameAndThreadCommentCount = `-- name: GetAllImagePostsByBoardIdWithAuthorUsernameAndThreadCommentCount :many
SELECT i.idimagepost, i.forumthread_idforumthread, i.users_idusers, i.imageboard_idimageboard, i.posted, i.description, i.thumbnail, i.fullimage, u.username, th.comments
FROM imagepost i
LEFT JOIN users u ON i.users_idusers = u.idusers
LEFT JOIN forumthread th ON i.forumthread_idforumthread = th.idforumthread
WHERE i.imageboard_idimageboard = ?
`

type GetAllImagePostsByBoardIdWithAuthorUsernameAndThreadCommentCountRow struct {
	Idimagepost              int32
	ForumthreadIdforumthread int32
	UsersIdusers             int32
	ImageboardIdimageboard   int32
	Posted                   sql.NullTime
	Description              sql.NullString
	Thumbnail                sql.NullString
	Fullimage                sql.NullString
	Username                 sql.NullString
	Comments                 sql.NullInt32
}

func (q *Queries) GetAllImagePostsByBoardIdWithAuthorUsernameAndThreadCommentCount(ctx context.Context, imageboardIdimageboard int32) ([]*GetAllImagePostsByBoardIdWithAuthorUsernameAndThreadCommentCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllImagePostsByBoardIdWithAuthorUsernameAndThreadCommentCount, imageboardIdimageboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllImagePostsByBoardIdWithAuthorUsernameAndThreadCommentCountRow
	for rows.Next() {
		var i GetAllImagePostsByBoardIdWithAuthorUsernameAndThreadCommentCountRow
		if err := rows.Scan(
			&i.Idimagepost,
			&i.ForumthreadIdforumthread,
			&i.UsersIdusers,
			&i.ImageboardIdimageboard,
			&i.Posted,
			&i.Description,
			&i.Thumbnail,
			&i.Fullimage,
			&i.Username,
			&i.Comments,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllImagePostsByIdWithAuthorUsernameAndThreadCommentCount = `-- name: GetAllImagePostsByIdWithAuthorUsernameAndThreadCommentCount :one
SELECT i.idimagepost, i.forumthread_idforumthread, i.users_idusers, i.imageboard_idimageboard, i.posted, i.description, i.thumbnail, i.fullimage, u.username, th.comments
FROM imagepost i
LEFT JOIN users u ON i.users_idusers = u.idusers
LEFT JOIN forumthread th ON i.forumthread_idforumthread = th.idforumthread
WHERE i.idimagepost = ?
`

type GetAllImagePostsByIdWithAuthorUsernameAndThreadCommentCountRow struct {
	Idimagepost              int32
	ForumthreadIdforumthread int32
	UsersIdusers             int32
	ImageboardIdimageboard   int32
	Posted                   sql.NullTime
	Description              sql.NullString
	Thumbnail                sql.NullString
	Fullimage                sql.NullString
	Username                 sql.NullString
	Comments                 sql.NullInt32
}

func (q *Queries) GetAllImagePostsByIdWithAuthorUsernameAndThreadCommentCount(ctx context.Context, idimagepost int32) (*GetAllImagePostsByIdWithAuthorUsernameAndThreadCommentCountRow, error) {
	row := q.db.QueryRowContext(ctx, getAllImagePostsByIdWithAuthorUsernameAndThreadCommentCount, idimagepost)
	var i GetAllImagePostsByIdWithAuthorUsernameAndThreadCommentCountRow
	err := row.Scan(
		&i.Idimagepost,
		&i.ForumthreadIdforumthread,
		&i.UsersIdusers,
		&i.ImageboardIdimageboard,
		&i.Posted,
		&i.Description,
		&i.Thumbnail,
		&i.Fullimage,
		&i.Username,
		&i.Comments,
	)
	return &i, err
}

const updateImageBoard = `-- name: UpdateImageBoard :exec
UPDATE imageboard SET title = ?, description = ?, imageboard_idimageboard = ? WHERE idimageboard = ?
`

type UpdateImageBoardParams struct {
	Title                  sql.NullString
	Description            sql.NullString
	ImageboardIdimageboard int32
	Idimageboard           int32
}

func (q *Queries) UpdateImageBoard(ctx context.Context, arg UpdateImageBoardParams) error {
	_, err := q.db.ExecContext(ctx, updateImageBoard,
		arg.Title,
		arg.Description,
		arg.ImageboardIdimageboard,
		arg.Idimageboard,
	)
	return err
}

const updateImagePostByIdForumThreadId = `-- name: UpdateImagePostByIdForumThreadId :exec
UPDATE imagepost SET forumthread_idforumthread = ? WHERE idimagepost = ?
`

type UpdateImagePostByIdForumThreadIdParams struct {
	ForumthreadIdforumthread int32
	Idimagepost              int32
}

func (q *Queries) UpdateImagePostByIdForumThreadId(ctx context.Context, arg UpdateImagePostByIdForumThreadIdParams) error {
	_, err := q.db.ExecContext(ctx, updateImagePostByIdForumThreadId, arg.ForumthreadIdforumthread, arg.Idimagepost)
	return err
}
