// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries-forum-cleanup.sql

package dbsqlite

import (
	"context"
)

const adminListOrphanComments = `-- name: AdminListOrphanComments :many
SELECT c.idcomments
FROM comments c
LEFT JOIN forumthread t ON c.forumthread_id = t.idforumthread
WHERE t.idforumthread IS NULL
`

func (q *Queries) AdminListOrphanComments(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, adminListOrphanComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var idcomments int64
		if err := rows.Scan(&idcomments); err != nil {
			return nil, err
		}
		items = append(items, idcomments)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrphanForumThreads = `-- name: AdminListOrphanForumThreads :many
SELECT t.idforumthread
FROM forumthread t
LEFT JOIN forumtopic ft ON t.forumtopic_idforumtopic = ft.idforumtopic
WHERE ft.idforumtopic IS NULL
`

func (q *Queries) AdminListOrphanForumThreads(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, adminListOrphanForumThreads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var idforumthread int64
		if err := rows.Scan(&idforumthread); err != nil {
			return nil, err
		}
		items = append(items, idforumthread)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteThreadsByTopicID = `-- name: DeleteThreadsByTopicID :exec
DELETE FROM forumthread WHERE forumtopic_idforumtopic = ?
`

func (q *Queries) DeleteThreadsByTopicID(ctx context.Context, forumtopicIdforumtopic int64) error {
	_, err := q.db.ExecContext(ctx, deleteThreadsByTopicID, forumtopicIdforumtopic)
	return err
}
