-- +goose Up
ALTER TABLE preferences
    ADD COLUMN IF NOT EXISTS page_size INT NOT NULL DEFAULT 15;

ALTER TABLE linkerCategory
    ADD COLUMN IF NOT EXISTS position INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sortorder INT NOT NULL DEFAULT 0;

-- ALTER TABLE blogs
    MODIFY written DATETIME NOT NULL DEFAULT NOW();

DROP TABLE IF EXISTS sidTable;

CREATE TABLE IF NOT EXISTS schema_version (
version INT NOT NULL
);

CREATE TABLE IF NOT EXISTS subscriptions (
id INTEGER PRIMARY KEY AUTOINCREMENT,
users_idusers INT NOT NULL,
item_type TEXT NOT NULL,
target_id INT NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pending_emails (
id INTEGER PRIMARY KEY AUTOINCREMENT,
to_email TEXT NOT NULL,
subject TEXT NOT NULL,
body TEXT NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
sent_at DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
id INTEGER PRIMARY KEY AUTOINCREMENT,
users_idusers INT NOT NULL,
link TEXT,
message TEXT,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
read_at DATETIME DEFAULT NULL
);

ON DUPLICATE KEY UPDATE version = VALUES(version);