-- +goose Up
ALTER TABLE imageboard
    ADD COLUMN IF NOT EXISTS approval_required TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE imagepost
    ADD COLUMN IF NOT EXISTS approved TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS file_size INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS banned_ips (
id INTEGER PRIMARY KEY AUTOINCREMENT,
ip_net TEXT NOT NULL,
reason TEXT,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
expires_at DATETIME DEFAULT NULL,
canceled_at DATETIME DEFAULT NULL,
UNIQUE (ip_net)
);

CREATE TABLE IF NOT EXISTS template_overrides (
name TEXT NOT NULL,
body TEXT NOT NULL,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS audit_log (
id INTEGER PRIMARY KEY AUTOINCREMENT,
users_idusers INT NOT NULL,
action TEXT NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS passwd_algorithm TEXT DEFAULT NULL;

UPDATE users SET passwd_algorithm = 'md5' WHERE passwd_algorithm IS NULL;