-- +goose Up
ALTER TABLE imageboard
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;

ALTER TABLE forumcategory
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;

ALTER TABLE forumtopic
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;

ALTER TABLE forumthread
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;

ALTER TABLE siteNews
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;

ALTER TABLE faq
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;

ALTER TABLE faqCategories
    ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;