-- +goose Up
ALTER TABLE imageboard ADD COLUMN deleted_at DATETIME DEFAULT NULL;
ALTER TABLE forumcategory ADD COLUMN deleted_at DATETIME DEFAULT NULL;
ALTER TABLE forumtopic ADD COLUMN deleted_at DATETIME DEFAULT NULL;
ALTER TABLE forumthread ADD COLUMN deleted_at DATETIME DEFAULT NULL;
ALTER TABLE siteNews ADD COLUMN deleted_at DATETIME DEFAULT NULL;
ALTER TABLE faq ADD COLUMN deleted_at DATETIME DEFAULT NULL;
ALTER TABLE faqCategories ADD COLUMN deleted_at DATETIME DEFAULT NULL;
UPDATE schema_version SET version = 10;