-- +goose Up
ALTER TABLE subscriptions
    ADD COLUMN IF NOT EXISTS method TEXT NOT NULL DEFAULT 'internal',
    ADD COLUMN IF NOT EXISTS pattern TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS worker_errors (
id INTEGER PRIMARY KEY AUTOINCREMENT,
message TEXT NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE pending_emails ADD COLUMN IF NOT EXISTS html_body TEXT;