-- +goose Up
ALTER TABLE subscriptions ADD COLUMN method TEXT NOT NULL DEFAULT 'internal';
ALTER TABLE subscriptions ADD COLUMN pattern TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS worker_errors (
id INTEGER PRIMARY KEY AUTOINCREMENT,
message TEXT NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE pending_emails ADD COLUMN html_body TEXT;
UPDATE schema_version SET version = 11;