-- Allow NULL language references
ALTER TABLE blogs ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE blogs ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE comments ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE comments ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE faq ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE faq ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE forumcategory ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE forumcategory ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE forumtopic ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE forumtopic ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE linker ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE linker ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE linker_queue ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE linker_queue ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE preferences ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE preferences ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE site_news ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE site_news ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE user_language ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE user_language ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE writing ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE writing ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE deactivated_comments ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE deactivated_comments ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE deactivated_writings ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE deactivated_writings ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE deactivated_blogs ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE deactivated_blogs ALTER COLUMN language_idlanguage DROP DEFAULT;
ALTER TABLE deactivated_linker ALTER COLUMN language_idlanguage DROP NOT NULL;
ALTER TABLE deactivated_linker ALTER COLUMN language_idlanguage DROP DEFAULT;

UPDATE blogs SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE comments SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE faq SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE forumcategory SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE forumtopic SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE linker SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE linker_queue SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE preferences SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE site_news SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE user_language SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE writing SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE deactivated_comments SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE deactivated_writings SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE deactivated_blogs SET language_idlanguage = NULL WHERE language_idlanguage = 0;
UPDATE deactivated_linker SET language_idlanguage = NULL WHERE language_idlanguage = 0;

-- Update schema version
UPDATE schema_version SET version = 59 WHERE version = 58;
