-- +goose Up
ALTER TABLE blogs ADD COLUMN timezone TINYTEXT DEFAULT NULL;
ALTER TABLE deactivated_blogs ADD COLUMN timezone TINYTEXT DEFAULT NULL;
ALTER TABLE site_news ADD COLUMN timezone TINYTEXT DEFAULT NULL;
ALTER TABLE imagepost ADD COLUMN timezone TINYTEXT DEFAULT NULL;
ALTER TABLE deactivated_imageposts ADD COLUMN timezone TINYTEXT DEFAULT NULL;
ALTER TABLE linker ADD COLUMN timezone TINYTEXT DEFAULT NULL;
ALTER TABLE linker_queue ADD COLUMN timezone TINYTEXT DEFAULT NULL;
ALTER TABLE deactivated_linker ADD COLUMN timezone TINYTEXT DEFAULT NULL;
ALTER TABLE faq_revisions ADD COLUMN timezone TINYTEXT DEFAULT NULL;


