ALTER TABLE faq ADD COLUMN deleted_at DATETIME DEFAULT NULL;
ALTER TABLE faq_categories ADD COLUMN deleted_at DATETIME DEFAULT NULL;
ALTER TABLE forumcategory ADD COLUMN deleted_at DATETIME DEFAULT NULL;
