-- Ensure deleted_at column exists on content tables
ALTER TABLE linker ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;
ALTER TABLE writing ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;
ALTER TABLE imagepost ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL;
