-- +goose Up
CREATE TABLE IF NOT EXISTS api_keys (
id INTEGER PRIMARY KEY AUTOINCREMENT,
users_idusers int NOT NULL,
api_key TEXT NOT NULL,
name TEXT NOT NULL,
scopes TEXT NOT NULL,
expires_at DATETIME DEFAULT NULL,
last_used_at DATETIME DEFAULT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
revoked_at DATETIME DEFAULT NULL,
UNIQUE (api_key)
);
UPDATE schema_version SET version = 89;