package admin

const (
	TemplateRequestQueuePage        = "admin/requestQueuePage.gohtml"
	TemplateRequestArchivePage      = "admin/requestArchivePage.gohtml"
	TemplateRequestPage             = "admin/requestPage.gohtml"
	TemplateEmailFailedPage         = "admin/emailFailedPage.gohtml"
	TemplateUserForumPage           = "userForumPage.gohtml"
	TemplateEmailQueuePage          = "admin/emailQueuePage.gohtml"
	TemplateMaintenancePage         = "admin/maintenancePage.gohtml"
	TemplateUserImagebbsPage        = "userImagebbsPage.gohtml"
	TemplateUserSubscriptionsPage   = "userSubscriptionsPage.gohtml"
	TemplateServerStatsPage         = "admin/serverStatsPage.gohtml"
	TemplateIPBanPage               = "ipBanPage.gohtml"
	TemplateSiteSettingsPage        = "admin/siteSettingsPage.gohtml"
	TemplateRolesPage               = "admin/rolesPage.gohtml"
	TemplateRunTaskPage             = "runTaskPage.gohtml"
	TemplateUserWritingsPage        = "admin/userWritingsPage.gohtml"
	TemplateUsageStatsPage          = "admin/usageStatsPage.gohtml"
	TemplateExternalLinksPage       = "admin/externalLinksPage.gohtml"
	TemplateCommentsPage            = "admin/commentsPage.gohtml"
	TemplateRoleGrantAddPage        = "adminRoleGrantAddPage.gohtml"
	TemplateCommentPage             = "admin/commentPage.gohtml"
	TemplateUserBlogsPage           = "admin/userBlogsPage.gohtml"
	TemplateEmailTemplateListPage   = "admin/emailTemplateListPage.gohtml"
	TemplateEmailTemplateEditPage   = "admin/emailTemplateEditPage.gohtml"
	TemplateAdminUserPage           = "admin/adminUserPage.gohtml"
	TemplateLinkRemapPage           = "admin/linkRemapPage.gohtml"
	TemplateAuditLogPage            = "auditLogPage.gohtml"
	TemplateUserLinkerPage          = "userLinkerPage.gohtml"
	TemplateRolePage                = "adminRolePage.gohtml"
	TemplateUserListPage            = "userList.gohtml"
	TemplateGrantAddPage            = "grantAddPage.gohtml"
	TemplateFilesPage               = "admin/adminFilesPage.gohtml"
	TemplateEmailSentPage           = "admin/emailSentPage.gohtml"
	TemplateUserCommentsPage        = "userCommentsPage.gohtml"
	TemplateAnnouncementsPage       = "admin/announcementsPage.gohtml"
	TemplatePageSizePage            = "admin/pageSizePage.gohtml"
	TemplateEmailTestPage           = "admin/emailTestPage.gohtml"
	TemplateGrantsPage              = "admin/grantsPage.gohtml"
	TemplateGrantPage               = "grantPage.gohtml"
	TemplateDeactivatedCommentsPage = "admin/deactivatedCommentsPage.gohtml"
	TemplateNotificationsPage       = "admin/notificationsPage.gohtml"
	TemplateRoleEditPage            = "admin/roleEditPage.gohtml"
	TemplateUserGrantAddPage        = "adminUserGrantAddPage.gohtml"
	TemplateUserGrantsPage          = "admin/userGrantsPage.gohtml"
	TemplateDLQPage                 = "admin/dlqPage.gohtml"
)
