package admin

import "github.com/arran4/goa4web/internal/tasks"

// RegisterTasks returns admin related tasks.
func (h *Handlers) RegisterTasks() []tasks.NamedTask {
	return []tasks.NamedTask{
		addAnnouncementTask,
		deleteAnnouncementTask,
		resendQueueTask,
		deleteQueueTask,
		bulkResendQueueTask,
		bulkDeleteQueueTask,
		resendSentEmailTask,
		retrySentEmailTask,
		saveTemplateTask,
		deleteTemplateTask,
		testTemplateTask,
		deleteDLQTask,
		markReadTask,
		markUnreadTask,
		toggleNotificationReadTask,
		purgeSelectedNotificationsTask,
		purgeReadNotificationsTask,
		deleteNotificationTask,
		sendNotificationTask,
		addUserSubscriptionTask,
		updateUserSubscriptionTask,
		deleteUserSubscriptionTask,
		h.NewApplySubscriptionTemplateTask(),
		addIPBanTask,
		deleteIPBanTask,
		ipBanBulkTask,
		acceptRequestTask,
		rejectRequestTask,
		queryRequestTask,
		deleteCommentTask,
		editCommentTask,
		deactivateCommentTask,
		restoreCommentTask,
		userForcePasswordChangeTask,
		userSendResetEmailTask,
		roleGrantCreateTask,
		roleGrantDeleteTask,
		userGrantCreateTask,
		applyLinkRemapTask,
		imageCacheListTask,
		imageCachePruneTask,
		imageCacheDeleteTask,
		h.NewServerShutdownTask(),
	}
}
