// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries-image_cache.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPendingImageCacheEntry = `-- name: CreatePendingImageCacheEntry :exec
INSERT INTO image_cache_entries (
  id,
  source_url,
  source_kind,
  status,
  created_at,
  last_used_at,
  retry_count,
  next_attempt_at
) VALUES (?, ?, ?, 'pending', ?, ?, 0, ?)
ON DUPLICATE KEY UPDATE
  source_url = VALUES(source_url),
  source_kind = VALUES(source_kind),
  last_used_at = VALUES(last_used_at),
  next_attempt_at = VALUES(next_attempt_at)
`

type CreatePendingImageCacheEntryParams struct {
	ID            string
	SourceUrl     sql.NullString
	SourceKind    string
	CreatedAt     time.Time
	LastUsedAt    sql.NullTime
	NextAttemptAt sql.NullTime
}

func (q *Queries) CreatePendingImageCacheEntry(ctx context.Context, arg CreatePendingImageCacheEntryParams) error {
	_, err := q.db.ExecContext(ctx, createPendingImageCacheEntry,
		arg.ID,
		arg.SourceUrl,
		arg.SourceKind,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.NextAttemptAt,
	)
	return err
}

const deleteImageCacheEntry = `-- name: DeleteImageCacheEntry :exec
DELETE FROM image_cache_entries
WHERE id = ?
`

func (q *Queries) DeleteImageCacheEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteImageCacheEntry, id)
	return err
}

const getImageCacheEntry = `-- name: GetImageCacheEntry :one
SELECT id, source_url, source_kind, status, created_at, last_used_at, fetched_at, expires_at, content_expires_at, content_type, size_bytes, width, height, checksum, thumbnail_id, uploaded_image_id, error_message, retry_count, last_attempt_at, next_attempt_at
FROM image_cache_entries
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetImageCacheEntry(ctx context.Context, id string) (*ImageCacheEntry, error) {
	row := q.db.QueryRowContext(ctx, getImageCacheEntry, id)
	var i ImageCacheEntry
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.SourceKind,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.ContentExpiresAt,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Checksum,
		&i.ThumbnailID,
		&i.UploadedImageID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.LastAttemptAt,
		&i.NextAttemptAt,
	)
	return &i, err
}

const listDuePendingImageCacheEntries = `-- name: ListDuePendingImageCacheEntries :many
SELECT id, source_url, source_kind, status, created_at, last_used_at, fetched_at, expires_at, content_expires_at, content_type, size_bytes, width, height, checksum, thumbnail_id, uploaded_image_id, error_message, retry_count, last_attempt_at, next_attempt_at
FROM image_cache_entries
WHERE source_kind = 'remote'
  AND status = 'pending'
  AND retry_count < ?
  AND (next_attempt_at IS NULL OR next_attempt_at <= ?)
ORDER BY created_at ASC
LIMIT ?
`

type ListDuePendingImageCacheEntriesParams struct {
	RetryCount    int32
	NextAttemptAt sql.NullTime
	Limit         int32
}

func (q *Queries) ListDuePendingImageCacheEntries(ctx context.Context, arg ListDuePendingImageCacheEntriesParams) ([]*ImageCacheEntry, error) {
	rows, err := q.db.QueryContext(ctx, listDuePendingImageCacheEntries, arg.RetryCount, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ImageCacheEntry
	for rows.Next() {
		var i ImageCacheEntry
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.SourceKind,
			&i.Status,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.FetchedAt,
			&i.ExpiresAt,
			&i.ContentExpiresAt,
			&i.ContentType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Checksum,
			&i.ThumbnailID,
			&i.UploadedImageID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.LastAttemptAt,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredExternalImageCacheEntries = `-- name: ListExpiredExternalImageCacheEntries :many
SELECT id, source_url, source_kind, status, created_at, last_used_at, fetched_at, expires_at, content_expires_at, content_type, size_bytes, width, height, checksum, thumbnail_id, uploaded_image_id, error_message, retry_count, last_attempt_at, next_attempt_at
FROM image_cache_entries
WHERE source_kind = 'remote'
  AND status = 'ready'
  AND expires_at IS NOT NULL
  AND expires_at <= ?
ORDER BY expires_at ASC
LIMIT ?
`

type ListExpiredExternalImageCacheEntriesParams struct {
	ExpiresAt sql.NullTime
	Limit     int32
}

func (q *Queries) ListExpiredExternalImageCacheEntries(ctx context.Context, arg ListExpiredExternalImageCacheEntriesParams) ([]*ImageCacheEntry, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredExternalImageCacheEntries, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ImageCacheEntry
	for rows.Next() {
		var i ImageCacheEntry
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.SourceKind,
			&i.Status,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.FetchedAt,
			&i.ExpiresAt,
			&i.ContentExpiresAt,
			&i.ContentType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Checksum,
			&i.ThumbnailID,
			&i.UploadedImageID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.LastAttemptAt,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOldestUsedImageCacheEntries = `-- name: ListOldestUsedImageCacheEntries :many
SELECT id, source_url, source_kind, status, created_at, last_used_at, fetched_at, expires_at, content_expires_at, content_type, size_bytes, width, height, checksum, thumbnail_id, uploaded_image_id, error_message, retry_count, last_attempt_at, next_attempt_at
FROM image_cache_entries
WHERE status = 'ready'
ORDER BY COALESCE(last_used_at, created_at) ASC
LIMIT ?
`

func (q *Queries) ListOldestUsedImageCacheEntries(ctx context.Context, limit int32) ([]*ImageCacheEntry, error) {
	rows, err := q.db.QueryContext(ctx, listOldestUsedImageCacheEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ImageCacheEntry
	for rows.Next() {
		var i ImageCacheEntry
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.SourceKind,
			&i.Status,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.FetchedAt,
			&i.ExpiresAt,
			&i.ContentExpiresAt,
			&i.ContentType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Checksum,
			&i.ThumbnailID,
			&i.UploadedImageID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.LastAttemptAt,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordImageCacheFetchFailure = `-- name: RecordImageCacheFetchFailure :exec
UPDATE image_cache_entries
SET status = CASE WHEN retry_count + 1 >= ? THEN 'failed' ELSE 'pending' END,
    error_message = ?,
    retry_count = retry_count + 1,
    last_attempt_at = ?,
    next_attempt_at = CASE WHEN retry_count + 1 >= ? THEN NULL ELSE ? END
WHERE id = ?
`

type RecordImageCacheFetchFailureParams struct {
	RetryCount    int32
	ErrorMessage  sql.NullString
	LastAttemptAt sql.NullTime
	RetryCount_2  int32
	NextAttemptAt sql.NullTime
	ID            string
}

func (q *Queries) RecordImageCacheFetchFailure(ctx context.Context, arg RecordImageCacheFetchFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordImageCacheFetchFailure,
		arg.RetryCount,
		arg.ErrorMessage,
		arg.LastAttemptAt,
		arg.RetryCount_2,
		arg.NextAttemptAt,
		arg.ID,
	)
	return err
}

const touchImageCacheEntry = `-- name: TouchImageCacheEntry :exec
UPDATE image_cache_entries
SET last_used_at = ?
WHERE id = ?
`

type TouchImageCacheEntryParams struct {
	LastUsedAt sql.NullTime
	ID         string
}

func (q *Queries) TouchImageCacheEntry(ctx context.Context, arg TouchImageCacheEntryParams) error {
	_, err := q.db.ExecContext(ctx, touchImageCacheEntry, arg.LastUsedAt, arg.ID)
	return err
}

const upsertImageCacheEntry = `-- name: UpsertImageCacheEntry :exec
INSERT INTO image_cache_entries (
  id,
  source_url,
  source_kind,
  status,
  created_at,
  last_used_at,
  fetched_at,
  expires_at,
  content_expires_at,
  content_type,
  size_bytes,
  width,
  height,
  checksum,
  thumbnail_id,
  uploaded_image_id,
  error_message,
  retry_count,
  last_attempt_at,
  next_attempt_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  source_url = VALUES(source_url),
  source_kind = VALUES(source_kind),
  status = VALUES(status),
  last_used_at = VALUES(last_used_at),
  fetched_at = VALUES(fetched_at),
  expires_at = VALUES(expires_at),
  content_expires_at = VALUES(content_expires_at),
  content_type = VALUES(content_type),
  size_bytes = VALUES(size_bytes),
  width = VALUES(width),
  height = VALUES(height),
  checksum = VALUES(checksum),
  thumbnail_id = VALUES(thumbnail_id),
  uploaded_image_id = VALUES(uploaded_image_id),
  error_message = VALUES(error_message),
  retry_count = VALUES(retry_count),
  last_attempt_at = VALUES(last_attempt_at),
  next_attempt_at = VALUES(next_attempt_at)
`

type UpsertImageCacheEntryParams struct {
	ID               string
	SourceUrl        sql.NullString
	SourceKind       string
	Status           string
	CreatedAt        time.Time
	LastUsedAt       sql.NullTime
	FetchedAt        sql.NullTime
	ExpiresAt        sql.NullTime
	ContentExpiresAt sql.NullTime
	ContentType      sql.NullString
	SizeBytes        sql.NullInt64
	Width            sql.NullInt32
	Height           sql.NullInt32
	Checksum         sql.NullString
	ThumbnailID      sql.NullString
	UploadedImageID  sql.NullInt32
	ErrorMessage     sql.NullString
	RetryCount       int32
	LastAttemptAt    sql.NullTime
	NextAttemptAt    sql.NullTime
}

func (q *Queries) UpsertImageCacheEntry(ctx context.Context, arg UpsertImageCacheEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertImageCacheEntry,
		arg.ID,
		arg.SourceUrl,
		arg.SourceKind,
		arg.Status,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.ContentExpiresAt,
		arg.ContentType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.Checksum,
		arg.ThumbnailID,
		arg.UploadedImageID,
		arg.ErrorMessage,
		arg.RetryCount,
		arg.LastAttemptAt,
		arg.NextAttemptAt,
	)
	return err
}
