// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries-drafts.sql

package db

import (
	"context"
)

const createDraft = `-- name: CreateDraft :execlastid
INSERT INTO drafts (
    user_id, thread_id, name, content
) VALUES (?, ?, ?, ?)
`

type CreateDraftParams struct {
	UserID   int32
	ThreadID int32
	Name     string
	Content  string
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDraft,
		arg.UserID,
		arg.ThreadID,
		arg.Name,
		arg.Content,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteDraft = `-- name: DeleteDraft :exec
UPDATE drafts
SET deleted_at = NOW()
WHERE id = ? AND user_id = ?
`

type DeleteDraftParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteDraft(ctx context.Context, arg DeleteDraftParams) error {
	_, err := q.db.ExecContext(ctx, deleteDraft, arg.ID, arg.UserID)
	return err
}

const getDraft = `-- name: GetDraft :one
SELECT id, user_id, thread_id, name, content, created_at, updated_at, deleted_at
FROM drafts
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type GetDraftParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) GetDraft(ctx context.Context, arg GetDraftParams) (*Draft, error) {
	row := q.db.QueryRowContext(ctx, getDraft, arg.ID, arg.UserID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ThreadID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const listDraftsForThread = `-- name: ListDraftsForThread :many
SELECT id, user_id, thread_id, name, content, created_at, updated_at, deleted_at
FROM drafts
WHERE thread_id = ? AND user_id = ? AND deleted_at IS NULL
`

type ListDraftsForThreadParams struct {
	ThreadID int32
	UserID   int32
}

func (q *Queries) ListDraftsForThread(ctx context.Context, arg ListDraftsForThreadParams) ([]*Draft, error) {
	rows, err := q.db.QueryContext(ctx, listDraftsForThread, arg.ThreadID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Draft
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ThreadID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDraft = `-- name: UpdateDraft :exec
UPDATE drafts
SET name = ?, content = ?
WHERE id = ? AND user_id = ?
`

type UpdateDraftParams struct {
	Name    string
	Content string
	ID      int32
	UserID  int32
}

func (q *Queries) UpdateDraft(ctx context.Context, arg UpdateDraftParams) error {
	_, err := q.db.ExecContext(ctx, updateDraft,
		arg.Name,
		arg.Content,
		arg.ID,
		arg.UserID,
	)
	return err
}
