// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries-auditlog.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const adminAuditLogActionSummary = `-- name: AdminAuditLogActionSummary :many
SELECT a.action, COUNT(*) AS total
FROM audit_log a
LEFT JOIN users u ON a.users_idusers = u.idusers
WHERE u.username LIKE ?
  AND a.action LIKE ?
  AND a.path LIKE ?
  AND (? IS NULL OR a.created_at >= ?)
  AND (? IS NULL OR a.created_at <= ?)
GROUP BY a.action
ORDER BY total DESC, a.action ASC
`

type AdminAuditLogActionSummaryParams struct {
	Username  sql.NullString
	Action    string
	Section   string
	StartTime sql.NullTime
	EndTime   sql.NullTime
}

type AdminAuditLogActionSummaryRow struct {
	Action string
	Total  int64
}

func (q *Queries) AdminAuditLogActionSummary(ctx context.Context, arg AdminAuditLogActionSummaryParams) ([]*AdminAuditLogActionSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, adminAuditLogActionSummary,
		arg.Username,
		arg.Action,
		arg.Section,
		arg.StartTime,
		arg.StartTime,
		arg.EndTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AdminAuditLogActionSummaryRow
	for rows.Next() {
		var i AdminAuditLogActionSummaryRow
		if err := rows.Scan(&i.Action, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAuditLogs = `-- name: AdminListAuditLogs :many
SELECT a.id, a.users_idusers, a.action, a.path, a.details, a.data, a.created_at, u.username
FROM audit_log a
LEFT JOIN users u ON a.users_idusers = u.idusers
WHERE u.username LIKE ?
  AND a.action LIKE ?
  AND a.path LIKE ?
  AND (? IS NULL OR a.created_at >= ?)
  AND (? IS NULL OR a.created_at <= ?)
ORDER BY a.id DESC
LIMIT ? OFFSET ?
`

type AdminListAuditLogsParams struct {
	Username  sql.NullString
	Action    string
	Section   string
	StartTime sql.NullTime
	EndTime   sql.NullTime
	Limit     int32
	Offset    int32
}

type AdminListAuditLogsRow struct {
	ID           int32
	UsersIdusers int32
	Action       string
	Path         string
	Details      sql.NullString
	Data         sql.NullString
	CreatedAt    time.Time
	Username     sql.NullString
}

func (q *Queries) AdminListAuditLogs(ctx context.Context, arg AdminListAuditLogsParams) ([]*AdminListAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListAuditLogs,
		arg.Username,
		arg.Action,
		arg.Section,
		arg.StartTime,
		arg.StartTime,
		arg.EndTime,
		arg.EndTime,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AdminListAuditLogsRow
	for rows.Next() {
		var i AdminListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UsersIdusers,
			&i.Action,
			&i.Path,
			&i.Details,
			&i.Data,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (users_idusers, action, path, details, data) VALUES (?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	UsersIdusers int32
	Action       string
	Path         string
	Details      sql.NullString
	Data         sql.NullString
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.UsersIdusers,
		arg.Action,
		arg.Path,
		arg.Details,
		arg.Data,
	)
	return err
}
