// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries-writings.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const assignWritingThisThreadId = `-- name: AssignWritingThisThreadId :exec
UPDATE writing SET forumthread_id = ? WHERE idwriting = ?
`

type AssignWritingThisThreadIdParams struct {
	ForumthreadID int32
	Idwriting     int32
}

func (q *Queries) AssignWritingThisThreadId(ctx context.Context, arg AssignWritingThisThreadIdParams) error {
	_, err := q.db.ExecContext(ctx, assignWritingThisThreadId, arg.ForumthreadID, arg.Idwriting)
	return err
}

const fetchAllCategoriesForUser = `-- name: FetchAllCategoriesForUser :many
WITH RECURSIVE role_ids(id) AS (
    SELECT ur.role_id AS id FROM user_roles ur WHERE ur.users_idusers = ?
    UNION
    SELECT r2.id
    FROM role_ids ri
    JOIN grants g ON g.role_id = ri.id AND g.section = 'role' AND g.active = 1
    JOIN roles r2 ON r2.name = g.action
)
SELECT wc.idwritingcategory, wc.writing_category_id, wc.title, wc.description
FROM writing_category wc
WHERE EXISTS (
    SELECT 1 FROM grants g
    WHERE g.section='writing'
      AND g.item='category'
      AND g.action='see'
      AND g.active=1
      AND g.item_id = wc.idwritingcategory
      AND (g.user_id = ? OR g.user_id IS NULL)
      AND (g.role_id IS NULL OR g.role_id IN (SELECT id FROM role_ids))
  )
`

type FetchAllCategoriesForUserParams struct {
	ViewerID int32
	UserID   sql.NullInt32
}

func (q *Queries) FetchAllCategoriesForUser(ctx context.Context, arg FetchAllCategoriesForUserParams) ([]*WritingCategory, error) {
	rows, err := q.db.QueryContext(ctx, fetchAllCategoriesForUser, arg.ViewerID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WritingCategory
	for rows.Next() {
		var i WritingCategory
		if err := rows.Scan(
			&i.Idwritingcategory,
			&i.WritingCategoryID,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWritingCategoriesForUser = `-- name: GetAllWritingCategoriesForUser :many
WITH RECURSIVE role_ids(id) AS (
    SELECT ur.role_id AS id FROM user_roles ur WHERE ur.users_idusers = ?
    UNION
    SELECT r2.id
    FROM role_ids ri
    JOIN grants g ON g.role_id = ri.id AND g.section = 'role' AND g.active = 1
    JOIN roles r2 ON r2.name = g.action
)
SELECT wc.idwritingcategory, wc.writing_category_id, wc.title, wc.description
FROM writing_category wc
WHERE wc.writing_category_id = ?
  AND EXISTS (
    SELECT 1 FROM grants g
    WHERE g.section='writing'
      AND g.item='category'
      AND g.action='see'
      AND g.active=1
      AND g.item_id = wc.idwritingcategory
      AND (g.user_id = ? OR g.user_id IS NULL)
      AND (g.role_id IS NULL OR g.role_id IN (SELECT id FROM role_ids))
    )
`

type GetAllWritingCategoriesForUserParams struct {
	ViewerID          int32
	Writingcategoryid int32
	UserID            sql.NullInt32
}

func (q *Queries) GetAllWritingCategoriesForUser(ctx context.Context, arg GetAllWritingCategoriesForUserParams) ([]*WritingCategory, error) {
	rows, err := q.db.QueryContext(ctx, getAllWritingCategoriesForUser, arg.ViewerID, arg.Writingcategoryid, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WritingCategory
	for rows.Next() {
		var i WritingCategory
		if err := rows.Scan(
			&i.Idwritingcategory,
			&i.WritingCategoryID,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWritingsByUser = `-- name: GetAllWritingsByUser :many
SELECT w.idwriting, w.users_idusers, w.forumthread_id, w.language_idlanguage, w.writing_category_id, w.title, w.published, w.writing, w.abstract, w.private, w.deleted_at, u.username,
    (SELECT COUNT(*) FROM comments c WHERE c.forumthread_id=w.forumthread_id AND w.forumthread_id != 0) AS Comments
FROM writing w
LEFT JOIN users u ON w.users_idusers = u.idusers
WHERE w.users_idusers = ?
ORDER BY w.published DESC
`

type GetAllWritingsByUserRow struct {
	Idwriting          int32
	UsersIdusers       int32
	ForumthreadID      int32
	LanguageIdlanguage int32
	WritingCategoryID  int32
	Title              sql.NullString
	Published          sql.NullTime
	Writing            sql.NullString
	Abstract           sql.NullString
	Private            sql.NullBool
	DeletedAt          sql.NullTime
	Username           sql.NullString
	Comments           int64
}

func (q *Queries) GetAllWritingsByUser(ctx context.Context, usersIdusers int32) ([]*GetAllWritingsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWritingsByUser, usersIdusers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllWritingsByUserRow
	for rows.Next() {
		var i GetAllWritingsByUserRow
		if err := rows.Scan(
			&i.Idwriting,
			&i.UsersIdusers,
			&i.ForumthreadID,
			&i.LanguageIdlanguage,
			&i.WritingCategoryID,
			&i.Title,
			&i.Published,
			&i.Writing,
			&i.Abstract,
			&i.Private,
			&i.DeletedAt,
			&i.Username,
			&i.Comments,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicWritings = `-- name: GetPublicWritings :many
SELECT w.idwriting, w.users_idusers, w.forumthread_id, w.language_idlanguage, w.writing_category_id, w.title, w.published, w.writing, w.abstract, w.private, w.deleted_at
FROM writing w
WHERE w.private = 0
ORDER BY w.published DESC
LIMIT ? OFFSET ?
`

type GetPublicWritingsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPublicWritings(ctx context.Context, arg GetPublicWritingsParams) ([]*Writing, error) {
	rows, err := q.db.QueryContext(ctx, getPublicWritings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Writing
	for rows.Next() {
		var i Writing
		if err := rows.Scan(
			&i.Idwriting,
			&i.UsersIdusers,
			&i.ForumthreadID,
			&i.LanguageIdlanguage,
			&i.WritingCategoryID,
			&i.Title,
			&i.Published,
			&i.Writing,
			&i.Abstract,
			&i.Private,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicWritingsByUser = `-- name: GetPublicWritingsByUser :many
SELECT w.idwriting, w.users_idusers, w.forumthread_id, w.language_idlanguage, w.writing_category_id, w.title, w.published, w.writing, w.abstract, w.private, w.deleted_at, u.username,
    (SELECT COUNT(*) FROM comments c WHERE c.forumthread_id=w.forumthread_id AND w.forumthread_id != 0) AS Comments
FROM writing w
LEFT JOIN users u ON w.users_idusers = u.idusers
WHERE w.private = 0 AND w.users_idusers = ?
ORDER BY w.published DESC
LIMIT ? OFFSET ?
`

type GetPublicWritingsByUserParams struct {
	UsersIdusers int32
	Limit        int32
	Offset       int32
}

type GetPublicWritingsByUserRow struct {
	Idwriting          int32
	UsersIdusers       int32
	ForumthreadID      int32
	LanguageIdlanguage int32
	WritingCategoryID  int32
	Title              sql.NullString
	Published          sql.NullTime
	Writing            sql.NullString
	Abstract           sql.NullString
	Private            sql.NullBool
	DeletedAt          sql.NullTime
	Username           sql.NullString
	Comments           int64
}

func (q *Queries) GetPublicWritingsByUser(ctx context.Context, arg GetPublicWritingsByUserParams) ([]*GetPublicWritingsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPublicWritingsByUser, arg.UsersIdusers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetPublicWritingsByUserRow
	for rows.Next() {
		var i GetPublicWritingsByUserRow
		if err := rows.Scan(
			&i.Idwriting,
			&i.UsersIdusers,
			&i.ForumthreadID,
			&i.LanguageIdlanguage,
			&i.WritingCategoryID,
			&i.Title,
			&i.Published,
			&i.Writing,
			&i.Abstract,
			&i.Private,
			&i.DeletedAt,
			&i.Username,
			&i.Comments,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicWritingsInCategory = `-- name: GetPublicWritingsInCategory :many
SELECT w.idwriting, w.users_idusers, w.forumthread_id, w.language_idlanguage, w.writing_category_id, w.title, w.published, w.writing, w.abstract, w.private, w.deleted_at, u.Username,
    (SELECT COUNT(*) FROM comments c WHERE c.forumthread_id=w.forumthread_id AND w.forumthread_id != 0) as Comments
FROM writing w
LEFT JOIN users u ON w.Users_Idusers=u.idusers
WHERE w.private = 0 AND w.writing_category_id=?
ORDER BY w.published DESC
LIMIT ? OFFSET ?
`

type GetPublicWritingsInCategoryParams struct {
	WritingCategoryID int32
	Limit             int32
	Offset            int32
}

type GetPublicWritingsInCategoryRow struct {
	Idwriting          int32
	UsersIdusers       int32
	ForumthreadID      int32
	LanguageIdlanguage int32
	WritingCategoryID  int32
	Title              sql.NullString
	Published          sql.NullTime
	Writing            sql.NullString
	Abstract           sql.NullString
	Private            sql.NullBool
	DeletedAt          sql.NullTime
	Username           sql.NullString
	Comments           int64
}

func (q *Queries) GetPublicWritingsInCategory(ctx context.Context, arg GetPublicWritingsInCategoryParams) ([]*GetPublicWritingsInCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getPublicWritingsInCategory, arg.WritingCategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetPublicWritingsInCategoryRow
	for rows.Next() {
		var i GetPublicWritingsInCategoryRow
		if err := rows.Scan(
			&i.Idwriting,
			&i.UsersIdusers,
			&i.ForumthreadID,
			&i.LanguageIdlanguage,
			&i.WritingCategoryID,
			&i.Title,
			&i.Published,
			&i.Writing,
			&i.Abstract,
			&i.Private,
			&i.DeletedAt,
			&i.Username,
			&i.Comments,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWritingByIdForUserDescendingByPublishedDate = `-- name: GetWritingByIdForUserDescendingByPublishedDate :one
WITH RECURSIVE role_ids(id) AS (
    SELECT ur.role_id AS id FROM user_roles ur WHERE ur.users_idusers = ?
    UNION
    SELECT r2.id
    FROM role_ids ri
    JOIN grants g ON g.role_id = ri.id AND g.section = 'role' AND g.active = 1
    JOIN roles r2 ON r2.name = g.action
)
SELECT w.idwriting, w.users_idusers, w.forumthread_id, w.language_idlanguage, w.writing_category_id, w.title, w.published, w.writing, w.abstract, w.private, w.deleted_at, u.idusers AS WriterId, u.Username AS WriterUsername
FROM writing w
JOIN users u ON w.users_idusers = u.idusers
WHERE w.idwriting = ? AND (w.private = 0 OR EXISTS (
    SELECT 1 FROM grants g
    WHERE g.section='writing'
      AND g.item='article'
      AND g.action='view'
      AND g.active=1
      AND g.item_id = w.idwriting
      AND (g.user_id = ? OR g.user_id IS NULL)
      AND (g.role_id IS NULL OR g.role_id IN (SELECT id FROM role_ids))
))
ORDER BY w.published DESC
`

type GetWritingByIdForUserDescendingByPublishedDateParams struct {
	ViewerID  int32
	Idwriting int32
	UserID    sql.NullInt32
}

type GetWritingByIdForUserDescendingByPublishedDateRow struct {
	Idwriting          int32
	UsersIdusers       int32
	ForumthreadID      int32
	LanguageIdlanguage int32
	WritingCategoryID  int32
	Title              sql.NullString
	Published          sql.NullTime
	Writing            sql.NullString
	Abstract           sql.NullString
	Private            sql.NullBool
	DeletedAt          sql.NullTime
	Writerid           int32
	Writerusername     sql.NullString
}

func (q *Queries) GetWritingByIdForUserDescendingByPublishedDate(ctx context.Context, arg GetWritingByIdForUserDescendingByPublishedDateParams) (*GetWritingByIdForUserDescendingByPublishedDateRow, error) {
	row := q.db.QueryRowContext(ctx, getWritingByIdForUserDescendingByPublishedDate, arg.ViewerID, arg.Idwriting, arg.UserID)
	var i GetWritingByIdForUserDescendingByPublishedDateRow
	err := row.Scan(
		&i.Idwriting,
		&i.UsersIdusers,
		&i.ForumthreadID,
		&i.LanguageIdlanguage,
		&i.WritingCategoryID,
		&i.Title,
		&i.Published,
		&i.Writing,
		&i.Abstract,
		&i.Private,
		&i.DeletedAt,
		&i.Writerid,
		&i.Writerusername,
	)
	return &i, err
}

const getWritingsByIdsForUserDescendingByPublishedDate = `-- name: GetWritingsByIdsForUserDescendingByPublishedDate :many
WITH RECURSIVE role_ids(id) AS (
    SELECT ur.role_id AS id FROM user_roles ur WHERE ur.users_idusers = ?
    UNION
    SELECT r2.id
    FROM role_ids ri
    JOIN grants g ON g.role_id = ri.id AND g.section = 'role' AND g.active = 1
    JOIN roles r2 ON r2.name = g.action
)
SELECT w.idwriting, w.users_idusers, w.forumthread_id, w.language_idlanguage, w.writing_category_id, w.title, w.published, w.writing, w.abstract, w.private, w.deleted_at, u.idusers AS WriterId, u.username AS WriterUsername
FROM writing w
JOIN users u ON w.users_idusers = u.idusers
WHERE w.idwriting IN (/*SLICE:writingids*/?) AND (w.private = 0 OR EXISTS (
    SELECT 1 FROM grants g
    WHERE g.section='writing'
      AND g.item='article'
      AND g.action='view'
      AND g.active=1
      AND g.item_id = w.idwriting
      AND (g.user_id = ? OR g.user_id IS NULL)
      AND (g.role_id IS NULL OR g.role_id IN (SELECT id FROM role_ids))
  ) OR w.users_idusers = ?)
ORDER BY w.published DESC
`

type GetWritingsByIdsForUserDescendingByPublishedDateParams struct {
	ViewerID   int32
	Writingids []int32
	UserID     sql.NullInt32
}

type GetWritingsByIdsForUserDescendingByPublishedDateRow struct {
	Idwriting          int32
	UsersIdusers       int32
	ForumthreadID      int32
	LanguageIdlanguage int32
	WritingCategoryID  int32
	Title              sql.NullString
	Published          sql.NullTime
	Writing            sql.NullString
	Abstract           sql.NullString
	Private            sql.NullBool
	DeletedAt          sql.NullTime
	Writerid           int32
	Writerusername     sql.NullString
}

func (q *Queries) GetWritingsByIdsForUserDescendingByPublishedDate(ctx context.Context, arg GetWritingsByIdsForUserDescendingByPublishedDateParams) ([]*GetWritingsByIdsForUserDescendingByPublishedDateRow, error) {
	query := getWritingsByIdsForUserDescendingByPublishedDate
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ViewerID)
	if len(arg.Writingids) > 0 {
		for _, v := range arg.Writingids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:writingids*/?", strings.Repeat(",?", len(arg.Writingids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:writingids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.UserID)
	queryParams = append(queryParams, arg.ViewerID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetWritingsByIdsForUserDescendingByPublishedDateRow
	for rows.Next() {
		var i GetWritingsByIdsForUserDescendingByPublishedDateRow
		if err := rows.Scan(
			&i.Idwriting,
			&i.UsersIdusers,
			&i.ForumthreadID,
			&i.LanguageIdlanguage,
			&i.WritingCategoryID,
			&i.Title,
			&i.Published,
			&i.Writing,
			&i.Abstract,
			&i.Private,
			&i.DeletedAt,
			&i.Writerid,
			&i.Writerusername,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWriting = `-- name: InsertWriting :execlastid
INSERT INTO writing (writing_category_id, title, abstract, writing, private, language_idlanguage, published, users_idusers)
VALUES (?, ?, ?, ?, ?, ?, NOW(), ?)
`

type InsertWritingParams struct {
	WritingCategoryID  int32
	Title              sql.NullString
	Abstract           sql.NullString
	Writing            sql.NullString
	Private            sql.NullBool
	LanguageIdlanguage int32
	UsersIdusers       int32
}

func (q *Queries) InsertWriting(ctx context.Context, arg InsertWritingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertWriting,
		arg.WritingCategoryID,
		arg.Title,
		arg.Abstract,
		arg.Writing,
		arg.Private,
		arg.LanguageIdlanguage,
		arg.UsersIdusers,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertWritingCategory = `-- name: InsertWritingCategory :exec
INSERT INTO writing_category (writing_category_id, title, description)
VALUES (?, ?, ?)
`

type InsertWritingCategoryParams struct {
	WritingCategoryID int32
	Title             sql.NullString
	Description       sql.NullString
}

func (q *Queries) InsertWritingCategory(ctx context.Context, arg InsertWritingCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertWritingCategory, arg.WritingCategoryID, arg.Title, arg.Description)
	return err
}

const updateWriting = `-- name: UpdateWriting :exec
UPDATE writing
SET title = ?, abstract = ?, writing = ?, private = ?, language_idlanguage = ?
WHERE idwriting = ?
`

type UpdateWritingParams struct {
	Title              sql.NullString
	Abstract           sql.NullString
	Writing            sql.NullString
	Private            sql.NullBool
	LanguageIdlanguage int32
	Idwriting          int32
}

func (q *Queries) UpdateWriting(ctx context.Context, arg UpdateWritingParams) error {
	_, err := q.db.ExecContext(ctx, updateWriting,
		arg.Title,
		arg.Abstract,
		arg.Writing,
		arg.Private,
		arg.LanguageIdlanguage,
		arg.Idwriting,
	)
	return err
}

const updateWritingCategory = `-- name: UpdateWritingCategory :exec
UPDATE writing_category
SET title = ?, description = ?, writing_category_id = ?
WHERE idwritingCategory = ?
`

type UpdateWritingCategoryParams struct {
	Title             sql.NullString
	Description       sql.NullString
	WritingCategoryID int32
	Idwritingcategory int32
}

func (q *Queries) UpdateWritingCategory(ctx context.Context, arg UpdateWritingCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateWritingCategory,
		arg.Title,
		arg.Description,
		arg.WritingCategoryID,
		arg.Idwritingcategory,
	)
	return err
}
