// Code generated by sqlc. DO NOT EDIT.
// versions:
<<<<<<< HEAD
//   sqlc v1.30.0
=======
//   sqlc v1.26.0
>>>>>>> 585b27a2 (feat(forum): implement post appending within time window)
// source: queries-passkeys.sql

package db

import (
	"context"
	"database/sql"
)

const deletePasskey = `-- name: DeletePasskey :exec
DELETE FROM user_passkeys WHERE id = ? AND user_id = ?
`

type DeletePasskeyParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) error {
	_, err := q.db.ExecContext(ctx, deletePasskey, arg.ID, arg.UserID)
	return err
}

const getPasskeyByCredentialID = `-- name: GetPasskeyByCredentialID :one
SELECT id, user_id, name, backup_eligible, backup_state, credential_id, public_key, attestation_type, aaguid, sign_count, created_at, updated_at, last_used_at, expires_at FROM user_passkeys WHERE credential_id = ?
`

func (q *Queries) GetPasskeyByCredentialID(ctx context.Context, credentialID []byte) (*UserPasskey, error) {
	row := q.db.QueryRowContext(ctx, getPasskeyByCredentialID, credentialID)
	var i UserPasskey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BackupEligible,
		&i.BackupState,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Aaguid,
		&i.SignCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const getPasskeysByUserID = `-- name: GetPasskeysByUserID :many
SELECT id, user_id, name, backup_eligible, backup_state, credential_id, public_key, attestation_type, aaguid, sign_count, created_at, updated_at, last_used_at, expires_at FROM user_passkeys WHERE user_id = ?
`

func (q *Queries) GetPasskeysByUserID(ctx context.Context, userID int32) ([]*UserPasskey, error) {
	rows, err := q.db.QueryContext(ctx, getPasskeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserPasskey
	for rows.Next() {
		var i UserPasskey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.BackupEligible,
			&i.BackupState,
			&i.CredentialID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPasskey = `-- name: InsertPasskey :exec
INSERT INTO user_passkeys (
    user_id, name, backup_eligible, backup_state, credential_id, public_key, attestation_type, aaguid, sign_count
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertPasskeyParams struct {
	UserID          int32
	Name            string
	BackupEligible  sql.NullBool
	BackupState     sql.NullBool
	CredentialID    []byte
	PublicKey       []byte
	AttestationType string
	Aaguid          []byte
	SignCount       int32
}

func (q *Queries) InsertPasskey(ctx context.Context, arg InsertPasskeyParams) error {
	_, err := q.db.ExecContext(ctx, insertPasskey,
		arg.UserID,
		arg.Name,
		arg.BackupEligible,
		arg.BackupState,
		arg.CredentialID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Aaguid,
		arg.SignCount,
	)
	return err
}

const updatePasskeyAfterLogin = `-- name: UpdatePasskeyAfterLogin :exec
UPDATE user_passkeys
SET sign_count = ?,
    backup_eligible = COALESCE(backup_eligible, ?),
    backup_state = ?,
    last_used_at = CURRENT_TIMESTAMP
WHERE credential_id = ?
`

type UpdatePasskeyAfterLoginParams struct {
	SignCount      int32
	BackupEligible sql.NullBool
	BackupState    sql.NullBool
	CredentialID   []byte
}

func (q *Queries) UpdatePasskeyAfterLogin(ctx context.Context, arg UpdatePasskeyAfterLoginParams) error {
	_, err := q.db.ExecContext(ctx, updatePasskeyAfterLogin,
		arg.SignCount,
		arg.BackupEligible,
		arg.BackupState,
		arg.CredentialID,
	)
	return err
}
