// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries-comments-admin.sql

package db

import (
	"context"
)

const adminDeleteCommentsByThread = `-- name: AdminDeleteCommentsByThread :exec
DELETE comments, comments_search
FROM comments
LEFT JOIN comments_search ON comments_search.comment_id = comments.idcomments
WHERE comments.forumthread_id = ?
`

func (q *Queries) AdminDeleteCommentsByThread(ctx context.Context, forumthreadID int32) error {
	_, err := q.db.ExecContext(ctx, adminDeleteCommentsByThread, forumthreadID)
	return err
}

const adminHardDeleteComment = `-- name: AdminHardDeleteComment :exec
DELETE comments, comments_search
FROM comments
LEFT JOIN comments_search ON comments_search.comment_id = comments.idcomments
WHERE comments.idcomments = ?
`

func (q *Queries) AdminHardDeleteComment(ctx context.Context, idcomments int32) error {
	_, err := q.db.ExecContext(ctx, adminHardDeleteComment, idcomments)
	return err
}

const adminListBadComments = `-- name: AdminListBadComments :many
SELECT idcomments, forumthread_id, users_idusers, language_id, written, text, timezone, deleted_at, last_index FROM comments WHERE text IS NULL OR text = ''
`

func (q *Queries) AdminListBadComments(ctx context.Context) ([]*Comment, error) {
	rows, err := q.db.QueryContext(ctx, adminListBadComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.Idcomments,
			&i.ForumthreadID,
			&i.UsersIdusers,
			&i.LanguageID,
			&i.Written,
			&i.Text,
			&i.Timezone,
			&i.DeletedAt,
			&i.LastIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
