// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries-password_resets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO pending_passwords (user_id, passwd, passwd_algorithm, verification_code)
VALUES (?, ?, ?, ?)
`

type CreatePasswordResetParams struct {
	UserID           int32
	Passwd           string
	PasswdAlgorithm  string
	VerificationCode string
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset,
		arg.UserID,
		arg.Passwd,
		arg.PasswdAlgorithm,
		arg.VerificationCode,
	)
	return err
}

const getPasswordResetByCode = `-- name: GetPasswordResetByCode :one
SELECT id, user_id, passwd, passwd_algorithm, verification_code, created_at, verified_at
FROM pending_passwords
WHERE verification_code = ? AND verified_at IS NULL AND created_at > ?
`

type GetPasswordResetByCodeParams struct {
	VerificationCode string
	CreatedAt        time.Time
}

func (q *Queries) GetPasswordResetByCode(ctx context.Context, arg GetPasswordResetByCodeParams) (*PendingPassword, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByCode, arg.VerificationCode, arg.CreatedAt)
	var i PendingPassword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Passwd,
		&i.PasswdAlgorithm,
		&i.VerificationCode,
		&i.CreatedAt,
		&i.VerifiedAt,
	)
	return &i, err
}

const getPasswordResetByUser = `-- name: GetPasswordResetByUser :one
SELECT id, user_id, passwd, passwd_algorithm, verification_code, created_at, verified_at
FROM pending_passwords
WHERE user_id = ? AND verified_at IS NULL AND created_at > ?
ORDER BY created_at DESC
LIMIT 1
`

type GetPasswordResetByUserParams struct {
	UserID    int32
	CreatedAt time.Time
}

func (q *Queries) GetPasswordResetByUser(ctx context.Context, arg GetPasswordResetByUserParams) (*PendingPassword, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByUser, arg.UserID, arg.CreatedAt)
	var i PendingPassword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Passwd,
		&i.PasswdAlgorithm,
		&i.VerificationCode,
		&i.CreatedAt,
		&i.VerifiedAt,
	)
	return &i, err
}

const markPasswordResetVerified = `-- name: MarkPasswordResetVerified :exec
UPDATE pending_passwords SET verified_at = NOW() WHERE id = ?
`

func (q *Queries) MarkPasswordResetVerified(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetVerified, id)
	return err
}

const purgePasswordResetsBefore = `-- name: PurgePasswordResetsBefore :execresult
DELETE FROM pending_passwords
WHERE created_at < ? OR verified_at IS NOT NULL
`

// Remove password reset entries that have expired or were already verified
func (q *Queries) PurgePasswordResetsBefore(ctx context.Context, createdAt time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, purgePasswordResetsBefore, createdAt)
}

const systemDeletePasswordReset = `-- name: SystemDeletePasswordReset :exec
DELETE FROM pending_passwords WHERE id = ?
`

func (q *Queries) SystemDeletePasswordReset(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, systemDeletePasswordReset, id)
	return err
}

const systemDeletePasswordResetsByUser = `-- name: SystemDeletePasswordResetsByUser :execresult
DELETE FROM pending_passwords WHERE user_id = ?
`

// Delete all password reset entries for the given user and return the result
func (q *Queries) SystemDeletePasswordResetsByUser(ctx context.Context, userID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, systemDeletePasswordResetsByUser, userID)
}
