// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries-dlq.sql

package db

import (
	"context"
	"time"
)

const countDeadLettersSystem = `-- name: CountDeadLettersSystem :one
SELECT COUNT(*) FROM dead_letters
`

func (q *Queries) CountDeadLettersSystem(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeadLettersSystem)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeadLetterForAdmin = `-- name: DeleteDeadLetterForAdmin :exec
DELETE FROM dead_letters WHERE id = ?
`

func (q *Queries) DeleteDeadLetterForAdmin(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDeadLetterForAdmin, id)
	return err
}

const insertDeadLetterSystem = `-- name: InsertDeadLetterSystem :exec
INSERT INTO dead_letters (message) VALUES (?)
`

func (q *Queries) InsertDeadLetterSystem(ctx context.Context, message string) error {
	_, err := q.db.ExecContext(ctx, insertDeadLetterSystem, message)
	return err
}

const latestDeadLetterForAdmin = `-- name: LatestDeadLetterForAdmin :one
SELECT MAX(created_at) FROM dead_letters
`

func (q *Queries) LatestDeadLetterForAdmin(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, latestDeadLetterForAdmin)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const listDeadLettersForAdmin = `-- name: ListDeadLettersForAdmin :many
SELECT id, message, created_at FROM dead_letters
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) ListDeadLettersForAdmin(ctx context.Context, limit int32) ([]*DeadLetter, error) {
	rows, err := q.db.QueryContext(ctx, listDeadLettersForAdmin, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DeadLetter
	for rows.Next() {
		var i DeadLetter
		if err := rows.Scan(&i.ID, &i.Message, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDeadLettersBeforeForAdmin = `-- name: PurgeDeadLettersBeforeForAdmin :exec
DELETE FROM dead_letters WHERE created_at < ?
`

func (q *Queries) PurgeDeadLettersBeforeForAdmin(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, purgeDeadLettersBeforeForAdmin, createdAt)
	return err
}
