// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries-dlq.sql

package db

import (
	"context"
	"time"
)

const systemCountDeadLetters = `-- name: SystemCountDeadLetters :one
SELECT COUNT(*) FROM dead_letters
`

func (q *Queries) SystemCountDeadLetters(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, systemCountDeadLetters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const systemDeleteDeadLetter = `-- name: SystemDeleteDeadLetter :exec
DELETE FROM dead_letters WHERE id = ?
`

func (q *Queries) SystemDeleteDeadLetter(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, systemDeleteDeadLetter, id)
	return err
}

const systemGetDeadLetter = `-- name: SystemGetDeadLetter :one
SELECT id, message, created_at FROM dead_letters WHERE id = ?
`

func (q *Queries) SystemGetDeadLetter(ctx context.Context, id int32) (*DeadLetter, error) {
	row := q.db.QueryRowContext(ctx, systemGetDeadLetter, id)
	var i DeadLetter
	err := row.Scan(&i.ID, &i.Message, &i.CreatedAt)
	return &i, err
}

const systemInsertDeadLetter = `-- name: SystemInsertDeadLetter :exec
INSERT INTO dead_letters (message) VALUES (?)
`

// System query only used internally
func (q *Queries) SystemInsertDeadLetter(ctx context.Context, message string) error {
	_, err := q.db.ExecContext(ctx, systemInsertDeadLetter, message)
	return err
}

const systemLatestDeadLetter = `-- name: SystemLatestDeadLetter :one
SELECT MAX(created_at) FROM dead_letters
`

func (q *Queries) SystemLatestDeadLetter(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, systemLatestDeadLetter)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const systemListDeadLetters = `-- name: SystemListDeadLetters :many
SELECT id, message, created_at FROM dead_letters
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) SystemListDeadLetters(ctx context.Context, limit int32) ([]*DeadLetter, error) {
	rows, err := q.db.QueryContext(ctx, systemListDeadLetters, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DeadLetter
	for rows.Next() {
		var i DeadLetter
		if err := rows.Scan(&i.ID, &i.Message, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const systemPurgeDeadLettersBefore = `-- name: SystemPurgeDeadLettersBefore :exec
DELETE FROM dead_letters WHERE created_at < ?
`

func (q *Queries) SystemPurgeDeadLettersBefore(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, systemPurgeDeadLettersBefore, createdAt)
	return err
}

const systemUpdateDeadLetter = `-- name: SystemUpdateDeadLetter :exec
UPDATE dead_letters SET message = ? WHERE id = ?
`

type SystemUpdateDeadLetterParams struct {
	Message string
	ID      int32
}

func (q *Queries) SystemUpdateDeadLetter(ctx context.Context, arg SystemUpdateDeadLetterParams) error {
	_, err := q.db.ExecContext(ctx, systemUpdateDeadLetter, arg.Message, arg.ID)
	return err
}
